# Generated by Django 4.2.7 on 2024-06-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yulduz', models.IntegerField()),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('haqida', models.TextField()),
                ('muddati', models.IntegerField()),
                ('narxi', models.IntegerField()),
                ('mehmonxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mexmonxona', to='app.mehmonxona')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='app.transport')),
            ],
        ),
    ]
